# Generated by Django 5.1 on 2025-10-23 15:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_pasajero',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre completo del pasajero', max_length=100)),
                ('email', models.EmailField(help_text='Correo electrónico único del pasajero', max_length=254, unique=True)),
                ('telefono', models.IntegerField(help_text='Número de teléfono del pasajero')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de registro')),
                ('foto', models.ImageField(blank=True, help_text='Foto de perfil del pasajero', null=True, upload_to='fotos_pasajeros/')),
            ],
            options={
                'verbose_name': 'Usuario Pasajero',
                'verbose_name_plural': 'Usuarios Pasajeros',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_tarjeta', models.CharField(help_text='Número de tarjeta (solo últimos 4 dígitos visibles por seguridad)', max_length=16)),
                ('tipo_tarjeta', models.CharField(help_text='Ej: Visa, MasterCard, American Express', max_length=50)),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento (MM/AA)')),
                ('cvv', models.CharField(help_text='Código de seguridad (CVV)', max_length=4)),
                ('usuario_pasajero', models.ForeignKey(help_text='Usuario al que pertenece esta tarjeta', on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='app_Usuario_pasajero_tarjetas.usuario_pasajero')),
            ],
            options={
                'verbose_name': 'Tarjeta de Pago',
                'verbose_name_plural': 'Tarjetas de Pago',
            },
        ),
    ]
